SHINHAN_APP_KEY = "발급받은_신한_앱키"
SHINHAN_APP_SECRET = "발급받은_신한_앱시크릿"
REF_ACCOUNT_NO = "레퍼런스_계좌번호(11자리)"
PENSION_ACCOUNT_NO = "연금저축_계좌번호(11자리)"
GENERAL_ACCOUNT_NO = "종합계좌_계좌번호(11자리)"
GEMINI_API_KEY = "제미나이_API키"
GITHUB_TOKEN = "깃허브_토큰"
GITHUB_REPO = "깃허브_사용자명/저장소명"
